/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ghosts_Proyecto;

/**
 *
 * @author Jhair
 */
public class Menu_reportes extends javax.swing.JFrame {

    /**
     * Creates new form Menu_reportes
     */
    public static int randomio(int max){
        int numAleatorio = (int) (Math.random() * max) +1;
        return numAleatorio;
    }
    public Menu_reportes() {
        initComponents();
        
        setLocationRelativeTo(null);//esto hace que la panatalla aparezca en medio
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jb_jugadores = new javax.swing.JButton();
        jb_ranking = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_pantalla = new javax.swing.JTextArea();
        jb_regresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reportes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jb_jugadores.setText("Ultimos Juegos");
        jb_jugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_jugadoresActionPerformed(evt);
            }
        });
        getContentPane().add(jb_jugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 101, 160, 66));

        jb_ranking.setText("Ranking Jugadores");
        jb_ranking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_rankingActionPerformed(evt);
            }
        });
        getContentPane().add(jb_ranking, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 185, -1, 69));

        ta_pantalla.setColumns(20);
        ta_pantalla.setRows(5);
        jScrollPane1.setViewportView(ta_pantalla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 430, 265));

        jb_regresar.setText("Regresar");
        jb_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_regresarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 290, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ghosts_Proyecto/res/45D.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_regresarActionPerformed
        Menu_principal mp =new Menu_principal();
        mp.setVisible(true);
        this.dispose();//aca se cierra esta ventana actual
    }//GEN-LAST:event_jb_regresarActionPerformed

    private void jb_rankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_rankingActionPerformed
        ta_pantalla.setText("");//con esto se borra lo que esta escrito en el textArea (si es que hay algo escrito)
        ta_pantalla.append("\tRanking de jugadores\nUsuario\t\t\tPuntos\n");
        
        int puntosJugadores[] = new int[MainProyecto.usuarios.length];
        String jugadores[] = new String[MainProyecto.usuarios.length];
        //cree este arreglo para introducir los puntos de cada jugador aqui
        //tal vez de esta manera se me haga mas facil manipular las posiciones
        int a = 1;
        int auxPuntos; //con esta manipulo el cambio de posicion de los valores del arreglo 
        String auxUsuario;
        //en este ciclo envio los nombres de usario y los puntos a los arreglos que cree aqui
        for (int i = 0; i < MainProyecto.usuarios.length; i++) {
            if("".equals(MainProyecto.usuarios[i].getNombUsuario())){
                break;
            }
            jugadores[i] = MainProyecto.usuarios[i].getNombUsuario();
            puntosJugadores[i] = MainProyecto.usuarios[i].getPuntos();
        }
        //con estos dos ciclos cambie de posicion los valores del arreglo de mayor a menor
        for (int i = 0; i < MainProyecto.usuarios.length; i++) {
            if("".equals(MainProyecto.usuarios[i].getNombUsuario())){
                break;
            }
            for(int j = i + 1; j < MainProyecto.usuarios.length; j++){
                if(puntosJugadores[i] < puntosJugadores[j]){
                    auxPuntos = puntosJugadores[i];
                    auxUsuario = jugadores[i];
                    puntosJugadores[i] = puntosJugadores[j];
                    jugadores[i] = jugadores [j];
                    puntosJugadores[j] = auxPuntos;
                    jugadores[j] = auxUsuario;
                }
            }
        }
        //impresion de arreglos ordenados (usuarios y puntuacion)
        for (int i = 0; i < MainProyecto.usuarios.length; i++) {
            if("".equals(MainProyecto.usuarios[i].getNombUsuario())){
                break;
            }
            ta_pantalla.append(Integer.toString(a)+". "+jugadores[i]+":\t\t\t"+Integer.toString(puntosJugadores[i])+"\n");
            a++;
        }
    }//GEN-LAST:event_jb_rankingActionPerformed

    private void jb_jugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_jugadoresActionPerformed
        int a = 1;
        ta_pantalla.setText("");
        ta_pantalla.append("\tUltimos Juegos");
        for (int i = 9; i >= 0; i--) {
            if("".equals(Menu_InicioSesion.UsuarioActivo.getReporte(i))){
                continue;
            }
            ta_pantalla.append("\n"+a+". "+Menu_InicioSesion.UsuarioActivo.getReporte(i));
            System.out.println(Menu_InicioSesion.UsuarioActivo.getReporte(i));
            a++;
        }
    }//GEN-LAST:event_jb_jugadoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_jugadores;
    private javax.swing.JButton jb_ranking;
    private javax.swing.JButton jb_regresar;
    private javax.swing.JTextArea ta_pantalla;
    // End of variables declaration//GEN-END:variables
}
