/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ghosts_Proyecto;

/**
 *
 * @author Jhair
 */
public class Mi_perfil extends javax.swing.JFrame {

    /**
     * Creates new form Mi_perfil
     */
    public Mi_perfil() {
        initComponents();
        setLocationRelativeTo(null);//esto hace que la panatalla aparezca en medio
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_Pantalla = new javax.swing.JTextArea();
        jb_miperfil = new javax.swing.JButton();
        jb_password = new javax.swing.JButton();
        jb_eliminar = new javax.swing.JButton();
        jb_reg = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mi Perfil");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 19, 151, -1));

        ta_Pantalla.setEditable(false);
        ta_Pantalla.setColumns(20);
        ta_Pantalla.setRows(5);
        jScrollPane1.setViewportView(ta_Pantalla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 330, 184));

        jb_miperfil.setText("Ver perfil");
        jb_miperfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_miperfilActionPerformed(evt);
            }
        });
        getContentPane().add(jb_miperfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 150, -1));

        jb_password.setText("Cambiar Contraseña");
        jb_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(jb_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 180, -1));

        jb_eliminar.setText("Eliminar cuenta");
        jb_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 150, -1));

        jb_reg.setText("Regresar");
        jb_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_regActionPerformed(evt);
            }
        });
        getContentPane().add(jb_reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 150, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ghosts_Proyecto/res/MG_9730-copia.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_passwordActionPerformed
        cambio_p ns = new cambio_p();
        ns.setVisible(true);
        ns.setLocationRelativeTo(null);
        ta_Pantalla.setText(null);//borra el contenido anterior
        this.dispose();
    }//GEN-LAST:event_jb_passwordActionPerformed

    private void jb_miperfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_miperfilActionPerformed
        ta_Pantalla.append("Nombre de Usuario: \n"+Menu_InicioSesion.UsuarioActivo.getNombUsuario() + "\n");
        
        ta_Pantalla.append("Contraseña: \n"+Menu_InicioSesion.UsuarioActivo.getContra()+"\n");
        
        ta_Pantalla.append("Los puntos de "+Menu_InicioSesion.UsuarioActivo.getNombUsuario()+" son"+": \n"+Menu_InicioSesion.UsuarioActivo.getPuntos()+ "\n");
        
    }//GEN-LAST:event_jb_miperfilActionPerformed

    private void jb_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_regActionPerformed
       Menu_principal mp=new Menu_principal();
        mp.setVisible(true);
        ta_Pantalla.setText(null);//borra el contenido anterior
        this.dispose();
    }//GEN-LAST:event_jb_regActionPerformed

    private void jb_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_eliminarActionPerformed
        Eliminar_Usuario eu=new Eliminar_Usuario();
        eu.setVisible(true);
        ta_Pantalla.setText(null);//borra el contenido anterior
        this.dispose();
    }//GEN-LAST:event_jb_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mi_perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mi_perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mi_perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mi_perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mi_perfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_eliminar;
    private javax.swing.JButton jb_miperfil;
    private javax.swing.JButton jb_password;
    private javax.swing.JButton jb_reg;
    private javax.swing.JTextArea ta_Pantalla;
    // End of variables declaration//GEN-END:variables
}
//////
